name: codechallenge
services:
  my-application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - rabbitmq
  #  mongodb://localhost:27017/?authMechanism=DEFAULT
  mongo:
    image: mongo:6.0.15
    container_name: mongodb1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_DATABASE: mongodatabase

  #  http://localhost:15672
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"